language: java
jdk:
  - oraclejdk8
node_js:
  - "6"
install:
  - npm install
  - npm run get-uaa
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run start-uaa
  - npm run start-singular-app
  - touch test/tmp/selenium-debug.log
  - tail -f test/tmp/selenium-debug.log &
script:
  - npm run test
