addons:
  firefox: "49.0.2"
language: java
jdk:
  - oraclejdk8
install:
  - nvm install node
  - nvm use node
  - npm install
  - npm run get-uaa
before_script:
  - echo "Installing Chrome..."
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run start-uaa
  - npm run start-singular-app
  - touch test/tmp/selenium-debug.log
  - tail -f test/tmp/selenium-debug.log &
script:
  - npm run test
